name = "wedding-invitation"
main = "worker/index.js"
compatibility_date = "2026-10-03"

[[d1_databases]]
binding = "DB"
database_name = "listofguests"
database_id = "5cb031cb-8469-4c27-a46d-fe19e999570b"
migrations_dir = "migrations"

[vars]
ALLOWED_ORIGIN = "https://konstantin-anastasiya.ru"
